export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORISED: 'UNAUTHORISED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_USAGE_EXCEEDED: 'COUPON_USAGE_EXCEEDED',
  PINCODE_NOT_SERVICEABLE: 'PINCODE_NOT_SERVICEABLE',
  // Cart holds local-delivery-only products that cannot reach the destination pincode.
  // error.details.products lists exactly what the customer has to remove to proceed.
  LOCAL_DELIVERY_ONLY_UNAVAILABLE: 'LOCAL_DELIVERY_ONLY_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  CONFIG_NOT_READY: 'CONFIG_NOT_READY',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SHIPPING_PROVIDER_LOCK_VIOLATION: 'SHIPPING_PROVIDER_LOCK_VIOLATION'
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

