-- AddValue
ALTER TYPE "OpsActionType" ADD VALUE IF NOT EXISTS 'INVITE_REVOKED';
ALTER TYPE "OpsActionType" ADD VALUE IF NOT EXISTS 'USER_DEACTIVATED';
ALTER TYPE "OpsActionType" ADD VALUE IF NOT EXISTS 'USER_KEY_ROTATED';
